version: '3.8'

services:
  stylex-frontend:
    # Dấu chấm (.) nghĩa là tìm Dockerfile ngay tại thư mục này
    build: . 
    
    # Đặt tên cho container để dễ tìm
    container_name: stylex_frontend_container
    
    # Chuyển cổng: Vào 3000 (máy thật) -> Sang 80 (Docker)
    ports:
      - "3000:80"
    
    # Tự động khởi động lại nếu bị crash
    restart: always
    
    # Chỉnh múi giờ cho chuẩn Việt Nam (phòng hờ)
    environment:
      - TZ=Asia/Ho_Chi_Minh