services:
  db:
    image: postgres:17
    restart: always
    container_name: fashion_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_buffers=128MB -c max_connections=50
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"


  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fashion_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db 
    ports:
      - "127.0.0.1:8000:8000"
    command: fastapi run app/main.py --host 0.0.0.0 --port 8000 --workers 1

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     args:
  #       - VITE_API_URL=${VITE_API_URL}
  #   container_name: fashion_frontend
  #   restart: always
  #   ports:
  #     - "127.0.0.1:5173:80"

  adminer:
    image: adminer
    restart: always
    container_name: fashion_adminer
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    depends_on:
      - db

volumes:
  postgres_data: